service: aws-thumbnailer # NOTE: update this with your service name
custom:
  apigwBinary:
    types:           #list of mime-types
     - 'image/jpeg'
plugins:
 - serverless-apigw-binary
 - serverless-apigwy-binary
 - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  role: arn:aws:iam::333090321695:role/lambda-upload-photo
  environment:
    BUCKET: aws-thumbnailer-photos
    BUCKET_THUMBNAIL: aws-thumbnailer-photos-thumbnail

package:
  individually: true
  exclude:
   - node_modules/**
   - upload-photo/**
   - thumbnail-photo/**
   - download-photo/**

functions:
  upload:
    handler: upload-photo/handler.upload
    events:
     - http:
         path: photo
         method: post
    package:
      include:
        - upload-photo/**
  thumbnail:
    handler: thumbnail-photo/handler.thumbnail
    events:
     - s3:
         bucket: ${self:provider.environment.BUCKET}
         event: s3:ObjectCreated:*
    package:
      include:
        - thumbnail-photo/**
  download:
    handler: download-photo/handler.download
    events:
     - http:
         path: photo/{key}
         method: get
         contentHandling: CONVERT_TO_BINARY
         request:
            parameters:
              paths:
                key: true
    package:
      include:
        - download-photo/**

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_THUMBNAIL}
